### ISSUE TITLE
##[error]ENOENT: no such file or directory, open '/home/vsts/work/1/s/owaspzap/report.json'

### ISSUE THREAD

**Issue by XSniper001** [microsoft/CSEDevOps#32]
Please any help !!
![1](https://user-images.githubusercontent.com/86624958/163691684-cf7d5bc0-90be-4c2d-ae36-0f3f15fcd587.PNG)
![2](https://user-images.githubusercontent.com/86624958/163691688-e33df5a2-3a60-4309-b267-028fa6fd4bfd.PNG)
!

**Comment by adhiman-cf** [comment]
any update on it please?

**Comment by oZakari** [comment]
I am getting the same error. Seems to be specific to Azure Pipelines as I don't get any errors when attempting to run this task in my Release Definition.

**Comment by QuentinBeeckmans** [comment]
@oZakari Is it possible to have your yaml implementation? Because I have the same error in release pipeline. Thx!

**Comment by oZakari** [comment]
@QuentinBeeckmans This is the YAML for the task I am using in my classic release definition.

```yaml
steps:
 - task: CSE-DevOps.zap-scanner.custom-build-release-task.owaspzap@1
  displayName: 'ZAP Scanner'
  inputs:
    scantype: targetedScan
    url: 'https://tester.azurewebsites.net'
    port: 443`
```
